# SPDX-FileCopyrightText: 2022 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: 0BSD
branches:
  - v[0-9]+.[0-9]+.[0-9]+
  - main
  - name: next
    prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - '@semantic-release/github'
  - - '@semantic-release/exec'
    - verifyConditionsCmd: ~/.cargo/bin/semantic-release-cargo -v verify-conditions
      prepareCmd: ~/.cargo/bin/semantic-release-cargo -v prepare ${nextRelease.version}
      publishCmd: ~/.cargo/bin/semantic-release-cargo -vv publish --no-dirty
  - - '@semantic-release/git'
    - assets:
        - Cargo.toml
        - Cargo.lock
        - CHANGELOG.md
      message: 'chore(release): ${nextRelease.version} [skip ci]'
