# SPDX-FileCopyrightText: 2026 Ali Sajid Imami
#
# SPDX-License-Identifier: 0BSD

from_latest_tag = true
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"
pre = "next.*"

# cog.toml
pre_bump_hooks = [
    "cargo build --release",
    "echo 'bumping from {{latest|0.0.0}} to {{version|0.0.1}}'",
    "cargo set-version {{version|0.0.1}}",
]

# pre_bump_hooks = ["echo cargo set-version {{version}}", "cargo check --release"]

# post_bump_hooks = [
#     "git push",
#     "git push origin {{version}}",
#     "cargo publish --dry-run",
# ]


[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]
