# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: 0BSD
name: Security Audit
on:
  schedule:
    - cron: 0 0 1,15 * *
  push:
    branches:
      - "*"
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  workflow_dispatch:

permissions: read-all

jobs:
    security_audit:
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - name: Checkout
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

            - name: Install mise
              uses: jdx/mise-action@v2
              env:
                MISE_ENV: audit

            - name: Check cargo-audit exists
              run: . "$HOME/.cargo/env" & which cargo-audit & which cargo & cargo --list & echo $PATH & cargo audit --help

            - name: Security Audit
              run: cargo-audit audit
