# SPDX-FileCopyrightText: 2022 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: 0BSD
name: Next version release check
on:
  workflow_call:
    outputs:
      new_release:
        description: "Whether or not a new release needs to be published"
        value: ${{jobs.preflight.outputs.new_release}}
      new_release_version:
        description: "Whether or not a new release needs to be published"
        value: ${{jobs.preflight.outputs.new_release_version}}
      prerelease:
        description: "Whether or not a new release needs to be published"
        value: ${{jobs.preflight.outputs.prerelease}}
permissions:
  contents: read
jobs:
  preflight:
    name: Preflight Checks for Release
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{steps.new_release_check.outputs.new_release}}
      prerelease: ${{steps.new_release_check.outputs.prerelease}}
      new_release_version: ${{steps.new_release_check.outputs.new_release_version}}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup mise-en-place
        uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2
        with:
          install: true
          experimental: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Preflight checks for release
        id: new_release_check
        run: mise run get-next-release ${{github.events.base_ref}}
        shell: bash
