# SPDX-FileCopyrightText: 2022 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: 0BSD
name: Next version release check
on:
  workflow_call:
    outputs:
      new_release:
        description: "Whether or not a new release needs to be published"
        value: ${{jobs.preflight.outputs.new_release}}
      prerelease:
        description: "Whether or not a new release needs to be published"
        value: ${{jobs.preflight.outputs.prerelease}}
permissions:
  contents: read
jobs:
  preflight:
    name: Preflight Checks for Release
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{steps.new_release_check.outputs.new_release}}
      prerelease: ${{steps.new_release_check.outputs.prerelease}}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup mise-en-place
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
        with:
          install: true
          experimental: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Preflight checks for release
        id: new_release_check
        run: mise run get-next-version ${{github.event.head_ref}}
        shell: bash
